### ISSUE TITLE
Unable to create user Request or Response types for un-implemented API endpoints.

### ISSUE THREAD

**Issue by digitalengineering** [afterpay/sdk-php#14]
The SDK currently does not implement all API endpoints, e.g. https://developers.afterpay.com/afterpay-online/reference#get-payment-by-order-id and https://developers.afterpay.com/afterpay-online/reference#reverse-payment-by-token. If an SDK user would like to create their own `Request` types to implement those missing APIs, it is impossible to use the base `Request` as-is, due to these lines:

`src/HTTP/Request.php` line 517.
```php
        $preferred_response_class = str_replace('Afterpay\SDK\HTTP\Request', 'Afterpay\SDK\HTTP\Response', get_class($this));
        if (class_exists($preferred_response_class)) {
            $this->response = new $preferred_response_class();
        } else {
            $this->response = new Response();
        }
```
If the user has created a class `Usernamespace\SDK\HTTP\Request\GetPaymentByOrderId`, then the string replace function will not change anything. The conditional on the next line will be true, which means the response property will be set to the custom Request class.

In order to fix this issue, we could rewrite the above lines like so:

```php
        $class_name = get_class($this);
        $preferred_response_class = str_replace('Afterpay\SDK\HTTP\Request', 'Afterpay\SDK\HTTP\Response', $class_name);
        if (strpos($class_name, 'Afterpay\SDK\HTTP\Request') === 0 && class_exists($preferred_response_class)) {
            $this->response = new $preferred_response_class();
        } else {
            $this->response = new Response();
        }
```

Now, the automatic determination of the `Response` class will only be performed for Afterpay-created Request types.

**Comment by benfterpay** [comment]
Hi @digitalengineering,

Thanks for raising this; it's certainly a valid concern.

Ideally, there would not be any Afterpay API endpoints not covered by the Afterpay SDK for PHP. Instead of allowing the Request classes to be extended, another suggestion would be to update the SDK to provide coverage for the missing endpoints.

An internal ticket has now been raised to provide coverage for `GetPaymentByOrderId` and `ReversePaymentByToken`. A review of the API documentation will also be conducted to identify any other endpoints not covered by the SDK.

Open to any further suggestions or discussion.

Thank you.
